sudo: required
language: rust
dist: trusty
cache: cargo

addons:
  apt:
    packages:
      - libssl-dev
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - zlib1g-dev
      - libiberty-dev

rust:
  - stable

script: cargo test --all-features

after_success:
  - |
    wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
    tar xzf master.tar.gz &&
    cd kcov-master &&
    mkdir build &&
    cd build &&
    cmake .. &&
    make &&
    sudo make install &&
    cd ../.. &&
    rm -rf kcov-master &&
    cargo install cargo-kcov &&
    cargo kcov --lib --features extended-steganography --coveralls -- --exclude-pattern=/.cargo,/usr/lib,/.rustup,/build --verify &&
    echo "Uploaded code coverage"

matrix:
  allow_failures:
    - rust: nightly
